### ISSUE TITLE
[FEATURE] 레이아웃 구성

### ISSUE THREAD

**Issue by AAminha** [DONGA-ST-A/Frontend#1]
## 이슈 내용

공통 레이아웃 구성 및 메인 페이지 레이아웃 구성

## To-do

- [x] 공통 레이아웃 구성
  - [x] Header (Hicardi Logo & Navbar 들어갈 예정)
  - [x] Body
  - [x] Footer (아마도 기업정보 들어갈 예정)
- [x] 메인 페이지 레이아웃 구성
  - [x] 제품 소개 컴포넌트
  - [x] 활용/활용 사례/사용해야 하는 이유 시장 현황 컴포넌트
  - [x] 사용하고 있는 병원 등 정량 정보 컴포넌트
- [x] eslint 및 prettier 재설정

## 참고사항
![image](https://github.com/DONGA-ST-A/Frontend/assets/87255791/32aa1173-c751-42b9-8119-df4279e29695)
