### ISSUE TITLE
[FEATURE] 메인 페이지 레이아웃 구성

### ISSUE THREAD

**Issue by AAminha** [DONGA-ST-A/Frontend#2]
## 이슈 내용

메인 페이지 레이아웃 구성

## To-do

- [ ] 제품 소개 컴포넌트
- [ ] 활용/활용 사례/사용해야 하는 이유 시장 현황 컴포넌트
- [ ] 사용하고 있는 병원 등 정량 정보 컴포넌트

## 참고사항
![image](https://github.com/DONGA-ST-A/Frontend/assets/87255791/b80ddb88-5a6c-43ab-8ca8-e5ef9276b242)
