### ISSUE TITLE
[DESGIN] 메인페이지 수정

### ISSUE THREAD

**Issue by AAminha** [DONGA-ST-A/Frontend#27]
## 이슈 내용

피그마 디자인 반영하여 메인페이지 수정

## To-do

- [x] 그래프 gif 삽입
- [x] 기대 효과 컴포넌트 아이콘 삽입
- [x] 병원 컴포넌트 병원 로고 수정 및 텍스트 수정
