### ISSUE TITLE
[FEATURE] 구매하기 페이지 - 진입 화면 구현

### ISSUE THREAD

**Issue by AAminha** [DONGA-ST-A/Frontend#29]
## 이슈 내용

구매하기 페이지 - 진입 화면 구현

## To-do

- [ ] 배너 삽입
- [ ] 상품 카테고리
- [ ] 정렬 순서 (드롭다운)
- [ ] 상품 리스트
  - [ ] 품절된 상품 보여주기
  - [ ] 서버랑 연결해서 상품 정보 가져오기
  - [ ] 호버 > 이미지 커지기

**Comment by hoyyChoi** [comment]
<상품 클릭 시 세부 내용 페이지로 이동하도록 구현> 그냥 하나만 보여주도록 한다고 했지?

**Comment by AAminha** [comment]
응응 하나만! 그냥 상품 아무거나 클릭해도 다 하나의 상품으로 가도록 할까 고민 중
