### ISSUE TITLE
[FEATURE] 제품 상세 페이지 구현

### ISSUE THREAD

**Issue by hoyyChoi** [DONGA-ST-A/Frontend#37]
## 이슈 내용

제품 상세 페이지 구현

## To-do
- [ ] 제품 정보 및 구매하기 버튼 구현
- [ ] 제품 설명 카테고리
- [ ] 해당 id 값으로 서버 데이터 받아오기
- [ ] 이미지들로 레이아웃 구성
- [ ] carousel autopaly
- [ ] 전체상품 페이지 이동 버튼
