### ISSUE TITLE
[FEATURE] Footer 컴포넌트 구현

### ISSUE THREAD

**Issue by AAminha** [DONGA-ST-A/Frontend#4]
## 이슈 내용

Footer 컴포넌트 (기업정보) 구현

## To-do

- [x] 기존 하이카디 사이트의 Footer와 유사하게 구현
  - [x] 하이카디 로고
  - [x] 기업 정보
  - [x] 약관 링크 (실제 기능 X)
- [x] TOP 버튼 (플로팅)

## 참고사항
실제 하이카디 사이트와 피그마에 구현된 Footer가 살짝 달라서 피그마대로 구현하겠습니다!
