### ISSUE TITLE
[FIX] 메인 페이지 추가 수정 (아직 작성 중)

### ISSUE THREAD

**Issue by AAminha** [DONGA-ST-A/Frontend#41]
## 이슈 내용

1차 배포 후 메인 페이지 추가 수정

## To-do

- [ ] Header
  - [ ] 아래쪽 테두리 넣기 (피그마 Q&A 페이지 보면 잘 보임)
- [ ] 시장 현황
  - [ ] 기존 gif 이미지 안에 있던 글자 코드로 구현하기
  - [ ] gif 새로운 것으로 교체하기
