### ISSUE TITLE
[FIX] main Page & header & 크로스브라우징

### ISSUE THREAD

**Issue by hoyyChoi** [DONGA-ST-A/Frontend#53]
## 이슈 내용
- mainPage 수정
- header 수정
- 크로스 브라우징

## To-do

- [x] mainPage 캐러셀 이미지 추가
- [x] mainPage 비디오 추가
- [x] mainPage 캐러셀 버튼 이동
- [ ] 크로스 브라우징
- [x] header 활성화 상태 변경
- [x] header 워딩 변경
