### ISSUE TITLE
[FEATURE] 회사 소개 페이지 구현

### ISSUE THREAD

**Issue by AAminha** [DONGA-ST-A/Frontend#55]
## 이슈 내용

회사 소개 페이지 구현

## To-do

- [x] 한 줄 소개 컴포넌트 (company 컴포넌트)
- [x] 회사 소개 컴포넌트 (about 컴포넌트)
- [x] 사업 분야 컴포넌트 (business 컴포넌트)
- [x] 연혁 컴포넌트 (history 컴포넌트)
- [x] 더 알아보기 컴포넌트 (learnMore2 컴포넌트)
  - [x] 버튼 클릭 시 사이트 이동 버튼
