### ISSUE TITLE
[FEATURE] Header 컴포넌트 구현 

### ISSUE THREAD

**Issue by hoyyChoi** [DONGA-ST-A/Frontend#7]
## 이슈 내용
- Header 컴포넌트 구현 (navigation bar)
- inner 레이아웃 root에 잡아놓기

## To-do
- [x] 기존 하이카디 사이트의 Header와 유사하게 구현
- [x] 하아카디 로고
- [x] 카테고리 별 라우팅 적용
- [x] 로그인, 회원가입 버튼
- [ ] 검색창 활성화 (실질적 검색 x)
